#!/bin/bash
find -mindepth 1 -type d | wc -l[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[l[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[l[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[1[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D[D[D[D
